### ISSUE TITLE
Fix the should_deny_access_if_past_expiry unit-test

### ISSUE THREAD

**Issue by smitbmx** [ordercloud-api/ordercloud-dotnet-catalyst#49]
The unit-test `should_deny_access_if_past_expiry` is failing because of the next exception:
```
System.ArgumentException : IDX12401: Expires: 'System.DateTime' must be after NotBefore: 'System.DateTime'.
   at System.IdentityModel.Tokens.Jwt.JwtPayload.AddFirstPriorityClaims(String issuer, String audience, Nullable`1 notBefore, Nullable`1 expires, Nullable`1 issuedAt)
   at System.IdentityModel.Tokens.Jwt.JwtPayload..ctor(String issuer, String audience, IEnumerable`1 claims, Nullable`1 notBefore, Nullable`1 expires, Nullable`1 issuedAt)
   at System.IdentityModel.Tokens.Jwt.JwtPayload..ctor(String issuer, String audience, IEnumerable`1 claims, Nullable`1 notBefore, Nullable`1 expires)
   at 
```

Need to fix and keep all the unit tests in the green state.

**Comment by smitbmx** [comment]
The issue has been fixed.
